include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:
    # Kalite
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    always_declare_return_types: true
    # Güvenlik
    avoid_dynamic_calls: true
    # Flutter
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
